[package]
name = "annual_report_database"
version = "0.1.0"
authors = ["Thomas Niederberger <thomas@niederb.ch>"]
edition = "2018"

[dependencies]
reqwest = {version = "0.10.4", features = ["blocking"] }
csv = "1.1.3"
serde_derive = "1.0.106"
serde = "1.0.106"
clap = "2.33.0"
log = "0.4.8"
env_logger = "0.7.1"
chrono = "0.4.11"
simplelog = "0.7.6"
tokio = { version = "0.2", features = ["full"] }