[package]
name = "annual_report_downloader"
version = "0.1.0"
authors = ["Thomas Niederberger <thomas@niederb.ch>"]
edition = "2018"

[dependencies]
reqwest = "0.9.20"
csv = "1.1.1"
serde_derive = "1.0.99"
serde = "1.0.99"
clap = "2.33.0"
log = "0.4.8"
env_logger = "0.6.2"